version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=global_radio
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - global-radio-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - global-radio-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - global-radio-network

volumes:
  mongodb_data:

networks:
  global-radio-network:
    driver: bridge