services:
  # Backend API Service
  - type: web
    name: global-radio-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/
    autoDeploy: true
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URL
        sync: false
        # This should be set manually in Render dashboard to MongoDB Atlas connection string
        # Example: mongodb+srv://username:password@cluster.mongodb.net/global_radio
      - key: DB_NAME
        value: global_radio
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: false
    rootDir: backend

  # Frontend Static Site
  - type: web
    name: global-radio-frontend
    env: static
    region: oregon
    plan: starter
    buildCommand: yarn install && yarn build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    branch: main
    headers:
      # Security headers
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      # Cache headers for static assets
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      # SPA routing - all routes should serve index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: global-radio-backend
          property: host
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
    rootDir: frontend

# Note: Render doesn't offer managed MongoDB
# You'll need to:
# 1. Create a MongoDB Atlas cluster (free tier available)
# 2. Get the connection string
# 3. Set MONGO_URL environment variable in Render dashboard