# ============================================================
# Global Radio — Render Blueprint (render.yaml)
# ============================================================
services:
  # ----------------------------------------------------------
  # MongoDB • private service (pserv) + disk
  # ----------------------------------------------------------
  # - type:            pserv               # private service ➜ internal network only
  #   name:            mongodb
  #   runtime:         docker
  #   dockerfilePath:  Dockerfile.mongodb
  #   plan:            starter             # change to 'pro' if you need bigger CPU/RAM
  #   region:          oregon              # or frankfurt / ohio / singapore
  #   disk:
  #     name:          mongodb-data
  #     mountPath:     /data/db
  #     sizeGB:        2                   # pick a size that fits your data
  #   envVars:
  #     - key:   MONGO_INITDB_DATABASE
  #       value: global_radio

  # ----------------------------------------------------------
  # FastAPI / Django / Flask backend
  # ----------------------------------------------------------
  - type:            web
    name:            backend
    runtime:         docker
    rootDir:         .                   # context for the Dockerfile
    dockerfilePath:  Dockerfile.backend
    plan:            starter                # free • starter • standard • pro
    healthCheckPath: /healthz            # root-level health check endpoint
    # scaling:
    #   minInstances: 1
    #   maxInstances: 3
    #   targetCPUPercent: 80
    envVars:
      # direct literals
      - key:   DB_NAME
        value: global_radio
      # point to Mongo running above (internal address is the service name)
      - key:   MONGO_URL
        value: mongodb://mongodb:27017

  # ----------------------------------------------------------
  # React front-end (served by nginx in your Dockerfile)
  # ----------------------------------------------------------
  - type:            web
    name:            frontend
    runtime:         docker
    rootDir:         .
    dockerfilePath:  Dockerfile.frontend
    plan:            starter
    buildFilter:
      paths:
        - frontend/**
        - Dockerfile.frontend
        - nginx.conf
    buildCommand: |
      docker build -t frontend \
        --build-arg REACT_APP_BACKEND_URL=${BACKEND_URL} \
        -f Dockerfile.frontend .
    envVars:
      # Backend URL for React app
      - key:   REACT_APP_BACKEND_URL
        fromService:
          name:   backend
          type:   web
          property: hostport          # resolves to host:port
      # Nginx configuration
      - key:   BACKEND_URL
        fromService:
          name:   backend
          type:   web
          property: hostport          # resolves to host:port